spring.application.name=PanierMS
server.port=8050
#Data
spring.datasource.url=jdbc:mysql://localhost:3306/PanierDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.cloud.config.enabled=false
spring.cloud.config.fail-fast=true
#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring-jpa.show-sql=true
#serveur de decouverte
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/