spring.application.name=RessourceMicroService
spring.data.mongodb.uri=mongodb+srv://amiralaffet:mlJea8NIC0Kazobf@cluster0.revbo.mongodb.net/RessourceMicroService

### JPA / HIBERNATE ###
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
server.port=8082
#server.servlet.context-path=/Examenblanc


# Eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka