spring:
  cloud:
    gateway:
      routes:
        - id: ACCOMPAGNEMENTPFEMICROSERVICE
          uri: lb://ACCOMPAGNEMENTPFEMICROSERVICE
          predicates:
            - Path=/api/accompagnement/**  # Updated to include all sub-paths

        - id: PROJETMICROSERVICE
          uri: lb://PROJETMICROSERVICE
          predicates:
            - Path=/api/projets/**  # Updated to include all sub-paths
server:
  port: 9094
eureka:
  instance:
    hostname: localhost
